service: test-productizer

package:
  individually: true

provider:
  name: aws
  runtime: python3.9
  region: eu-north-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerImage: public.ecr.aws/sam/build-python3.9:latest
    layer: true
    slim: true

functions:
  app:
    package:
      artifact: dist/productizer-0.1.0.tar.gz
    handler: productizer.main.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: any
          path: /{proxy+}
