service: test-productizer

package:
  individually: true

provider:
  name: aws
  runtime: python3.9
  region: eu-north-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
functions:
  app:
    package:
      patterns:
        - "productizer/**"
        - "!requirements.txt"
        - "!package.json"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!.venv/**"
        - "!node_modules/**"
    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: any
          path: /{proxy+}
