# This workflow will install Python dependencies, run tests, lint and upload an artifact for the deployment phase
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# And for the deployment flow: https://www.viget.com/articles/automating-build-deploy-ci-cd-with-github-actions/

name: Build and test

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      PULUMI_ACCESS_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AUTHORIZATION_GW_ENDPOINT_URL:
        required: true

env:
  python-version: 3.9

jobs:
  build-test-deploy:
    name: "Build, test and deploy"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade awscli
          make install
      - name: Run lint check with black
        run: |
          make lint-check
      - name: Test with pytest
        run: |
          make test
      - name: Deploy with pulumi
        run: |
          make deploy-pulumi puluni_stack=virtualfinland/${{ inputs.environment }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          POETRY_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          POETRY_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          POETRY_AWS_REGION: ${{ secrets.AWS_REGION }}
          POETRY_AUTHORIZATION_GW_ENDPOINT_URL: ${{ secrets.AUTHORIZATION_GW_ENDPOINT_URL }}
