# This workflow will build and deploy the python app with serverless framerwork
# @see: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# @see: https://www.viget.com/articles/automating-build-deploy-ci-cd-with-github-actions/
name: Deploy Dev

on:
  push:
    branches: ["main"]

permissions:
  contents: read

env:
  python-version: 3.9

jobs:
  build-test-deploy:
    uses: Virtual-Finland-Development/testbed-test-productizer/.github/workflows/build-test-deploy.yml@main
    with:
      environment: dev
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AUTHORIZATION_GW_ENDPOINT_URL: ${{ secrets.AUTHORIZATION_GW_ENDPOINT_URL }}
