name: Deploy Staging

on:
  workflow_dispatch:
    branches: [main]

permissions:
  contents: read

env:
  python-version: 3.9

jobs:
  build-test-deploy:
    uses: Virtual-Finland-Development/testbed-test-productizer/.github/workflows/build-test-deploy.yml@main
    with:
      environment: staging
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      POETRY_AUTHORIZATION_GW_ENDPOINT_URL: ${{ secrets.AUTHORIZATION_GW_ENDPOINT_URL }}
