# This workflow will build and deploy the python app with serverless framerwork
# @see: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# @see: https://www.viget.com/articles/automating-build-deploy-ci-cd-with-github-actions/
name: Deploy Dev

on:
  workflow_call:
  push:
    branches: ["main"]

permissions:
  contents: read

env:
  python-version: 3.9

jobs:
  deploy:
    name: "Deploy"
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: Virtual-Finland-Development/testbed-test-productizer/.github/workflows/build-and-test.yml@main
        with:
          puluni_stack: virtualfinland/dev
      # deploy!
      - name: Deploy with pulumi
        run: |
          make deploy-pulumi puluni_stack=virtualfinland/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          POETRY_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          POETRY_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          POETRY_AWS_REGION: ${{ secrets.AWS_REGION }}
          POETRY_AUTHORIZATION_GW_ENDPOINT_URL: ${{ secrets.AUTHORIZATION_GW_ENDPOINT_URL }}
